// Which kinds of record (model names) a route is about, so a sweep can aim a request at a REAL id of the right kind. A hint only:
// a route with no entry is tried with a sample of every kind, so a new route is still swept; it just costs more requests.
const HINTS = [
  [/^\/api\/v1\/:id(\/status)?$|^\/api\/v1\/type\/|^\/api\/v1\/access\/users/, ["Admin"]],
  [/\/accounting\/account-groups/, ["AccountGroup"]],
  [/\/accounting\/fiscal-years/, ["FiscalYear"]],
  [/\/accounting\/(accounts|chart)/, ["LedgerAccount"]],
  [/\/accounting\/reports\/voucher/, ["Voucher"]],
  [/\/accounting\/returnable/, ["Transaction"]],
  [/\/accounting\/tax-codes/, ["TaxCode"]],
  [/\/accounting\/attachments/, ["Attachment"]],
  [/\/banking\/reconciliation\/lines/, ["BankStatementLine"]],
  [/\/banking\/reconciliation\/imports/, ["BankStatementImport"]],
  [/\/banking\/reconciliation\/matches/, ["BankMatch", "BankStatementLine"]],
  [/\/banking\/reconciliation\/reconciliations/, ["BankReconciliation"]],
  [/\/banking\/banks/, ["BankMaster"]],
  [/\/banking\/card-types/, ["CardType"]],
  [/\/banking\/cards/, ["CardMaster"]],
  [/\/banking\/cheques/, ["Cheque"]],
  [/\/einvoice\/(preview|submit)\//, ["Transaction"]],
  [/\/einvoice\/submissions/, ["EInvoiceSubmission"]],
  [/\/einvoice\/inbound/, ["InboundInvoice"]],
  [/\/einvoice\/parties/, ["Customer", "Vendor"]],
  [/\/batches/, ["StockBatch"]],
  [/\/vat-return\/returns/, ["VATReturn"]],
  [/\/reports\/vat/, ["VATReport"]],
  [/\/opening-balances\/accounts/, ["LedgerAccount"]],
  [/\/opening-balances\/parties/, ["Customer", "Vendor"]],
  [/\/opening-balances\/stock/, ["Stock"]],
  [/\/document-types/, ["DocumentType"]],
  [/\/branches/, ["Branch"]],
  [/\/quotations/, ["Quotation"]],
  [/\/delivery-notes\/from-order/, ["Transaction"]],
  [/\/delivery-notes/, ["DeliveryNote"]],
  [/\/document-flow\/customer/, ["Customer"]],
  [/\/messaging\/sends/, ["DocumentSend"]],
  [/\/messaging\/shares/, ["ShareLink"]],
  [/\/vendors\//, ["Vendor"]],
  [/\/customers\//, ["Customer"]],
  [/\/stock\/stock/, ["Stock"]],
  [/\/uom\/units/, ["UOM"]],
  [/\/uom\/conversions/, ["UOMConversion"]],
  [/\/transactions\/transactions/, ["Transaction"]],
  [/\/inventory\/inventory/, ["InventoryMovement"]],
  [/\/categories\/categories/, ["Category"]],
  [/\/staff\/staff/, ["Staff"]],
  [/\/vouchers\/vouchers/, ["Voucher"]],
  [/\/account\/account-vouchers/, ["Voucher"]],
  [/\/account-v2\/Transactor/, ["Transactor", "LedgerAccount"]],
  [/\/expense\/categories/, ["ExpenseCategory"]],
  [/\/ledger\/ledger\/vendor/, ["Vendor"]],
  [/\/ledger\/ledger\/customer/, ["Customer"]],
];
const modelsFor = (route) => (HINTS.find(([re]) => re.test(route.path)) || [])[1] || null;


module.exports = { HINTS, modelsFor };
